const database = [
	new Post(`Начало`, new Date(`2023-01-19 09:03`), `
		Начало моей персональной веб страницы.
	`, `event`),
	new Post(`Пара классов`, new Date(`2023-01-19 09:36`), `
		Написал пару полезных классов на Java Script, хотел оставить у себя в странице.
		\`\`\`
		\n//#region Random\n/**\n * A class that manages with randomness.\n */\nclass Random {\n\t/**\n\t * Gives a random number between min and max exclusively.\n\t * @param {Number} min A minimum value.\n\t * @param {Number} max A maximum value.\n\t * @returns A random float float.\n\t */\n\tstatic number(min, max) {\n\t\treturn Math.random() * (max - min) + min;\n\t}\n\t/**\n\t * Gives a random element from an array.\n\t * @template Type Elements type.\n\t * @param {Array<Type>} array Given array.\n\t * @returns An array element.\n\t */\n\tstatic element(array) {\n\t\treturn array[Math.floor(Random.number(0, array.length))];\n\t}\n\t/**\n\t * A function that returns random variant from cases.\n\t * @template Type Case type.\n\t * @param {Map<Type, Number>} cases Map of cases.\n\t * @returns Random case.\n\t */\n\tstatic case(cases) {\n\t\tconst summary = Array.from(cases).reduce((previous, current) => previous + current[1], 0);\n\t\tconst random = Random.number(0, summary);\n\t\tlet selection = undefined;\n\t\tlet start = 0;\n\t\tfor (const entry of cases) {\n\t\t\tconst end = start + entry[1];\n\t\t\tif (start <= random && random < end) {\n\t\t\t\tselection = entry[0];\n\t\t\t\tbreak;\n\t\t\t}\n\t\t\tstart = end;\n\t\t}\n\t\tif (typeof (selection) == \`undefined\`) {\n\t\t\tthrow new ReferenceError(\`Can't select value. Maybe stack is empty.\`);\n\t\t} else {\n\t\t\treturn selection;\n\t\t}\n\t}\n}\n//#endregion\n//#region Archive\n/**\n * A class for convenient data storage in local storage.\n * @template Notation Data type stored in archive.\n */\nclass Archive {\n\t/**\n\t * @param {String} path The path where the data should be stored.\n\t * @param {Notation?} initial Initial data.\n\t */\n\tconstructor(path, initial = null) {\n\t\tthis.#path = path;\n\t\tif (!localStorage.getItem(path) && initial) {\n\t\t\tlocalStorage.setItem(path, JSON.stringify(initial, undefined, \`\t\`));\n\t\t}\n\t}\n\t/** @type {String} */ #path;\n\t/**\n\t * The data stored in the archive.\n\t */\n\tget data() {\n\t\tconst item = localStorage.getItem(this.#path);\n\t\tif (item) {\n\t\t\treturn (/** @type {Notation} */ (JSON.parse(item)));\n\t\t} else {\n\t\t\tthrow new ReferenceError(\`Key '\${this.#path}' is undefined.\`);\n\t\t}\n\t}\n\t/**\n\t * The data stored in the archive.\n\t */\n\tset data(value) {\n\t\tlocalStorage.setItem(this.#path, JSON.stringify(value, undefined, \`\t\`));\n\t}\n\t/**\n\t * Function for receiving and transmitting data. Frequent use is not recommended based on optimization.\n\t * @param {(value: Notation) => Notation} action A function that transforms the results.\n\t */\n\tchange(action) {\n\t\tthis.data = action(this.data);\n\t}\n}\n//#endregion\n
		\`\`\`
	`, `code java-script`),
	new Post(`Сертификат Musixmatch`, new Date(`2023-01-20 20:47`), `
		Получил сертификат академии в [Musixmatch](https://www.musixmatch.com/)  
		![Сертификат](../resources/Graduate Certificate.jpg)
	`, `bounties photo`),
];